language: ruby

rvm:
  - 2.6.3

services:
  - postgresql

addons:
  firefox: latest

env:
  global:
    - RAILS_ENV=test
    - MOZ_HEADLESS=1

cache:
  yarn: true

before_install:
  - gem install bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn install
  - gem install bundle-audit

script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
  - bundle-audit check --update